# Generated by Django 3.1.1 on 2020-10-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_userhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
