# Generated by Django 3.1.1 on 2020-10-03 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_userhistory_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserHistory',
        ),
    ]
