# Generated by Django 3.1.1 on 2020-10-03 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_userhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhistory',
            name='updated',
        ),
    ]
